- alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: debug
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: warn
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: error
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: info
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''input_select.zigbee2mqtt_log_level'') }}'
      topic: zigbee2mqtt/bridge/config/log_level
  id: 0836866d1fd242d8b4fd765ec1c00252
- id: enable_zigbee_join
  alias: Enable Zigbee joining
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: switch.zigbee2mqtt_main_join
    service: switch.turn_on
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.start
  hide_entity: true
- id: disable_zigbee_join
  alias: Disable Zigbee joining
  hide_entity: true
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
- id: '1550993584515'
  alias: Frank dormir
  trigger:
  - entity_id: input_boolean.frank_cama
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: scene.frank_cama
    service: scene.turn_on
- id: '1558509588104'
  alias: Luz pasillo  - on
  trigger:
  - entity_id: binary_sensor.0x00158d000257f589_occupancy
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.0xf0d1b80000037209_light
    service: light.turn_on
- id: '1558509685957'
  alias: Luz bano - on
  trigger:
  - entity_id: binary_sensor.0x00158d0002d43d30_occupancy
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.luz_bano
    service: light.turn_on
- id: '1558510043368'
  alias: luz bano - off
  trigger:
  - entity_id: binary_sensor.0x00158d0002d43d30_occupancy
    for: 00:35:00
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.luz_bano
    service: light.turn_off
- id: '1560761839440'
  alias: Frank luces - on
  trigger:
  - entity_id: input_boolean.frank_luz
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: scene.frank_on
    service: scene.turn_on
- id: '1560762087189'
  alias: Frank luces - off
  trigger:
  - entity_id: input_boolean.frank_luz
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: scene.frank_off
    service: scene.turn_on
- id: '1560763893699'
  alias: Luces de Frank -- Iluminado
  trigger:
  - entity_id: input_select.luz_frank
    platform: state
    to: Iluminado
  condition: []
  action:
  - data:
      entity_id: scene.frank_on
    service: scene.turn_on
- id: '1560764362839'
  alias: Luces Frank - Apagado
  trigger:
  - entity_id: input_select.luz_frank
    platform: state
    to: Apagado
  condition: []
  action:
  - data:
      entity_id: scene.frank_off
    service: scene.turn_on
- id: '1560764409191'
  alias: Luces de Frank - Led
  trigger:
  - entity_id: input_select.luz_frank
    platform: state
    to: Led
  condition: []
  action:
  - data:
      entity_id: scene.leds_frank
    service: scene.turn_on
- id: '1560764467641'
  alias: Luces de Frank - Foco
  trigger:
  - entity_id: input_select.luz_frank
    platform: state
    to: Foco
  condition: []
  action:
  - data:
      entity_id: scene.foco_frank
    service: scene.turn_on
- id: '1560764539158'
  alias: Luces de Frank - Lampara
  trigger:
  - entity_id: input_select.luz_frank
    platform: state
    to: Lampara
  condition: []
  action:
  - data:
      entity_id: scene.frank_cama
    service: scene.turn_on
<<<<<<< HEAD
=======
- id: '1582445144702'
  alias: Luz lavanderia ON on arrival (Frank)
  description: Lavanderia lights turn on when Frank comes after dark
  trigger:
  - entity_id: device_tracker.life360_frank
    platform: state
    to: Home
  condition:
  - after: sunset
    condition: sun
  action:
  - entity_id: group.luz_lavado
    service: homeassistant.turn_on
>>>>>>> b323658d136d31f759cb3c0a2e72be4e616f18e0
- id: '1582445437430'
  alias: Turn on lavanderia with motion
  description: Turn on lavanderia lights with motion
  trigger:
<<<<<<< HEAD
  - entity_id: binary_sensor.0x00158d00028ab4a8_occupancy
=======
  - entity_id: binary_sensor.0x00158d0002e999d4_occupancy_2
>>>>>>> b323658d136d31f759cb3c0a2e72be4e616f18e0
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: group.luz_lavado
    service: homeassistant.turn_on
- id: '1582445667146'
  alias: Turn OFF lavanderia  if no motion
  description: Turn OFF ligths in lavanderia if no motion detected for 5 minutes
  trigger:
<<<<<<< HEAD
  - entity_id: binary_sensor.0x00158d00028ab4a8_occupancy
    for: 0:05:10
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: group.luz_lavado
    entity_id: group.luz_lavado
    service: homeassistant.turn_off
- id: '1583829898117'
  alias: '[new] turn off lavado when no motion'
  description: ''
  trigger:
  - entity_id: group.luz_lavado
    for: 0:00:10
    platform: state
    to: 'on'
  condition:
  - condition: device
    device_id: fadb39f69c0d4d2b838659c689f97c39
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d00028ab4a8_occupancy
    for:
      hours: 0
      minutes: 10
      seconds: 10
    type: is_no_motion
  action:
  - data:
      entity_id: group.luz_lavado
    entity_id: group.luz_lavado
    service: homeassistant.turn_off
=======
  - entity_id: group.luz_lavado
    for: 00:05:00
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.0x00158d0002e999d4_occupancy_2
