########
##
##  YamiFrankc's Home Assistant configuration.
## Everything here is open source and you can grab anything you want and use as you like
## You can contact me at Yami at yamifrankc.com
##############


homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml
  #uth_providers:
   #- type: legacy_api_password
    # api_password:  !secret http_api_password
  
# Example configuration.yaml entry
mobile_app:

# Configure a default setup of Home Assistant (frontend, api, etc)

wake_on_lan:

recorder:
  purge_interval: 2
  purge_keep_days: 5

map:

history:
logbook:



influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state


# entity_controller:
#   motion_light:
#     sensor: binary_sensor.0x00158d0002e999d4_occupancy_2
#     entity: light.0xf0d1b80000037e7f_light

# Cloud :) :) :) :) :)
cloud:

hacs:
  token: !secret hacs_token
  appdaemon: true
  python_script: true
  theme: true


config:

webhook:

zigbee2mqtt_networkmap:



panel_iframe:
   networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'
   grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: http://192.168.1.20:3000


stream:

# http:
 # api_password: !secret http_api_password


system_health:

sun:

notify:
  - name: Casa
    platform: simplepush
    device_key: !secret simplepush_device_key


# Enables the frontend
frontend:
   themes: !include_dir_merge_named themes

camera:




# Discover some devices automatically
discovery:

# MQTT
mqtt:
  discovery: true
  broker: a0d7b954-mqtt
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

scene: !include scenes.yaml

# blink:
#   username: !secret blink_username
#   password: !secret blink_password

# Sensors
sensor: !include sensors.yaml

zone: !include zones.yaml
speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload


# transmission:
#   host: !secret transmission_host
#   name: Transmission
#   scan_interval: 180
#   monitored_conditions:
#      - total_torrents
#      - completed_torrents
#      - started_torrents
#      - download_speed
#      - active_torrents

weather:
   - platform: darksky
     api_key: !secret darksky_api_key
     mode: daily


binary_sensor: !include binary_sensors.yaml



tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    language: es
    time_memory: 300
    base_url: !secret base_url

switch: !include  switches.yaml


light: !include lights.yaml

automation: !include automations.yaml
script: !include scripts.yaml

group:
  zigbee_group:
    view: false
    control: hidden
    name: zigbee2mqtt
    entities:
      - input_boolean.zigbee_permit_join
      - timer.zigbee_permit_join
      - sensor.zigbee2mqtt_bridge_state
      - switch.zigbee2mqtt_main_join
      - automation.enable_zigbee_joining
      - automation.disable_zigbee_joining
      - automation.disable_zigbee_joining_by_timer
      - input_select.zigbee2mqtt_log_level
      - automation.zigbee2mqtt_log_level

  familia:
     name: Familia
     entities:
      - device_tracker.life360_ma
      - device_tracker.life360_pa
      - device_tracker.life360_frank

  luz_frank:
    name: Luz Frank
    entities:
      - light.focote_1
      - light.frank
      - light.0xf0d1b80000037e7f_light

      
# Input select for zigbee2mqtt debug level
input_select:
  zigbee2mqtt_log_level:
    name: zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted
  luz_frank:
    name: Luz de frank
    options:
      - Iluminado
      - Apagado
      - Led
      - Foco
      - Lampara
    initial: Iluminado

# Input boolean for enabling/disabling joining
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  frank_cama:
    name: Luz para dormir
    initial: off
    icon: mdi:bed-empty
  frank_luz:
    name: Luz de frank
    initial: off

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 300
