homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
history:
logbook:


# Cloud :) :) :) :) :)
cloud:
  google_actions:
    filter:
      exclude_entities:
        - input_boolean.zigbee_permit_join
    entity_config:
       switch.lampara_frank:
         name: Lampara de Frank
         aliases:
           - Lamparita
         room: Cuarto Frank
       light.luz_frank:
         name: Luz Frank
         aliases:
           - Luz de Frank
         room: Cuarto Frank




config:

webhook:

zigbee2mqtt_networkmap:

panel_iframe:
   networkmap:
     title: 'Zigbee Map'
     url: '/local/zigbee2mqtt_networkmap/map.html'
     icon: 'mdi:graphql'
   cloud9:
      title: 'Cloud9'
      url: 'http://192.168.1.20:8321/ide.html'
      icon: 'mdi:code-braces'


stream:

http:
  api_password: !secret http_api_password


system_health:

sun:

notify:
  - name: Casa
    platform: simplepush
    device_key: !secret simplepush_device_key


# Enables the frontend
frontend:
   themes: !include themes.yaml

camera:
   - platform: mjpeg
     name: WyZEE
     mjpeg_url: http://192.168.1.20:8081
     still_image_url: http://192.168.1.20:8123/api/hassio_ingress/pFUgNVaxhwTr2phZNZCp0BS1cZi1yKxr5Iy6fIkdyNw/picture/1/current/



# Discover some devices automatically
discovery:

# MQTT
mqtt:
  discovery: true
  broker: a0d7b954-mqtt
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'


# Sensors
sensor:
  - platform: mqtt
    name: Zigbee2mqtt Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  - platform: rest
    name: Reporte
    json_attributes:
       - name
       - status
       - used_pct
       - is_decrypted
    resource: http://192.168.1.4/api/v1.0/storage/volume/SengokuNadeko/?format=json
    value_template: '{{ value_json.status }}'
    username: !secret fn_user
    password: !secret fn_password
    authentication: basic
    headers:
      Content-Type: application/json
  - platform: template
    sensors:
      fn_trunk_pct_used:
        value_template: '{{ states.sensor.reporte.attributes["used_pct"].title() }}'
        entity_id: sensor.fn_trunk_report

  - platform: rest
    name: Alerta Freenas
    resource: http://192.168.1.4/api/v1.0/system/alert/?format=json
    value_template: '{{ value_json[0].level }}'
    username: !secret fn_user
    password: !secret fn_password
    authentication: basic
    headers:
      Content-Type: application/json

  - platform: rest
    name: Freenas mensaje de alerta
    resource: http://192.168.1.4/api/v1.0/system/alert/?format=json
    value_template: '{{ value_json[0].message }}'
    username: !secret fn_user
    password: !secret fn_password
    authentication: basic
    headers:
      Content-Type: application/json

  - platform: rest
    name: Freenas version
    json_attributes:
      - fullversion
      - name
      - version
    resource: http://192.168.1.4/api/v1.0/system/version/?format=json
    value_template: '{{ value_json.fullversion }}'
    username: !secret fn_user
    password: !secret fn_password
    authentication: basic
    headers:
      Content-Type: application/json

speedtestdotnet:
  scan_interval:
    hours: 2
  monitored_conditions:
    - ping
    - download
    - upload


transmission:
  host: !secret transmission_host
  name: Transmission
  scan_interval: 180
  monitored_conditions:
     - total_torrents
     - completed_torrents
     - started_torrents
     - download_speed
     - active_torrents

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily


binary_sensor:
  - platform: mqtt
    state_topic: "tele/sonoff_rf_frank/RESULT"
    name: 'Movimiento Baño'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: 'E42CFE'
    payload_off: 'E42CF-E'
    device_class: motion
    qos: 1

  - platform: mqtt
    state_topic: "tele/sonoff_rf_frank/RESULT"
    name: 'Puerta Frank'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: '8115EE'
    payload_off: '8115E7'
    device_class: door
    qos: 1

  - platform: mqtt
    state_topic: "tele/sonoff_rf_sala/RESULT"
    name: 'Refrigerador atras'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: '18230A'
    payload_off: '18230E'
    device_class: door
    qos: 1

  - platform: mqtt
    state_topic: "tele/sonoff_rf_sala/RESULT"
    name: 'Alacena'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: '4CF5EE'
    payload_off: '4CF5E7'
    device_class: door
    qos: 1

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    language: es
    time_memory: 300
    base_url: !secret base_url

switch:
  - platform: mqtt
    name: "Lampara Frank"
    state_topic: "stat/sonoff_lampara_frank/POWER"
    command_topic: "cmnd/sonoff_lampara_frank/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Luz alacena"
    state_topic: "stat/sonoff_alacena/POWER"
    command_topic: "cmnd/sonoff_alacena/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Zigbee2mqtt Main join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"

  #- platform: broadlink
   # host: 192.168.1.14
   # mac: '78:0f:77:5a:dc:e2'

light:
  - platform: flux_led
    automatic_add: true

  - platform: mqtt
    name: "Luz Frank"
    command_topic: "cmnd/sonoff_Frank/power1"
    state_topic: "stat/sonoff_Frank/POWER1"
    availability_topic: tele/sonoff_Frank/LWT
    payload_available: Online
    payload_not_available: Offline
    qos: 1
    payload_off: "OFF"
    payload_on: "ON"
    retain: false

  - platform: mqtt
    name: "Luz Baño"
    command_topic: "cmnd/sonoff_bathroom/power"
    state_topic: "stat/sonoff_bathroom/POWER"
    availability_topic: tele/sonoff_bathroom/LWT
    payload_available: Online
    payload_not_available: Offline
    payload_off: "OFF"
    payload_on: "ON"
    retain: false


automation: !include automations.yaml
script: !include scripts.yaml

group:
  zigbee_group:
    view: false
    control: hidden
    name: Zigbee2mqtt
    entities:
      - input_boolean.zigbee_permit_join
      - timer.zigbee_permit_join
      - sensor.zigbee2mqtt_bridge_state
      - switch.zigbee2mqtt_main_join
      - automation.enable_zigbee_joining
      - automation.disable_zigbee_joining
      - automation.disable_zigbee_joining_by_timer
      - input_select.zigbee2mqtt_log_level
      - automation.zigbee2mqtt_log_level

# Input select for Zigbee2mqtt debug level
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted

# Input boolean for enabling/disabling joining
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
  frank_cama:
    name: Luz para dormir
    initial: off
    icon: mdi:bed-empty

# Timer for joining time remaining (120 sec = 2 min)
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 300
